//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWeb.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biz_MarketingInfo
    {
        public long ID { get; set; }
        public long Lsh { get; set; }
        public Nullable<long> TaskID { get; set; }
        public Nullable<int> WFState { get; set; }
        public string WFNextUserList { get; set; }
        public Nullable<long> FilesPKID { get; set; }
        public Nullable<long> CreateUserCode { get; set; }
        public string CreateUserName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<long> CreateDeptCode { get; set; }
        public string CreateDeptName { get; set; }
        public Nullable<long> BiddingCollectionLsh { get; set; }
        public string Xmmc { get; set; }
        public string Jsdw { get; set; }
        public string JsdwLxrdh { get; set; }
        public string Zbdl { get; set; }
        public string ZbdlLxrdh { get; set; }
        public Nullable<System.DateTime> Bmsj { get; set; }
        public string Zzyq { get; set; }
        public string Kcdw { get; set; }
        public string Sjdw { get; set; }
        public string Wz { get; set; }
        public string Npzj { get; set; }
        public string XmjlName { get; set; }
        public string Remark { get; set; }
        public string Gcdd { get; set; }
        public Nullable<long> SsbmCode { get; set; }
        public string SsbmName { get; set; }
        public Nullable<long> SsdwLsh { get; set; }
        public string SsdwName { get; set; }
        public Nullable<long> HzrID { get; set; }
        public string HzrName { get; set; }
    }
}
